environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"

    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"

    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"

services:
  - mysql
  - mssql2016

platform:
  - x86

install:
  - "curl -fsS -o lxml.whl 'http://www.lfd.uci.edu/~gohlke/pythonlibs/tugh5y6k/lxml-3.7.3-cp27-cp27m-win_amd64.whl' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://www.lfd.uci.edu/~gohlke/pythonlibs/' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed"
  - "%PYTHON%\\python.exe -m pip install lxml.whl"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install django==%DJANGO_VERSION%"
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "%PYTHON%\\python.exe manage.py test"
