environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    # -------- PYTHON 2.7, Django 1.10 --------

    - PYTHON: "27"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "27"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "27"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "27"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 2.7, Django 1.11b1 --------

    - PYTHON: "27"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "27"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "27"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "27"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.4, Django 1.10 --------

    - PYTHON: "34"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "34"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "34"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "34"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 3.4, Django 1.11b1 --------

    - PYTHON: "34"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "34"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "34"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "34"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.5, Django 1.10 --------

    - PYTHON: "35"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "35"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "35"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "35"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 3.5, Django 1.11b1 --------

    - PYTHON: "35"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "35"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "35"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "35"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.6, Django 1.11b1 --------

    - PYTHON: "36"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "36"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "36"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "36"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57


platform:
  - x86

init:
- cmd: net start %SQL%

install:
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install lxml-3.7.3-cp27-cp27m-win_amd64.whl"
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install mysqlclient-1.3.10-cp27-cp27m-win_amd64.whl"
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install -r requirements.txt"
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install django==%DJANGO_VERSION%"
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "C:\\Python%PYTHON%-x64\\python.exe manage.py test"
