environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"

    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"

    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"

services:
  - mysql
  - mssql2012sp1
  - mssql2014
  - mssql2016

platform:
  - x86

install:
  - "%PYTHON%\\python.exe -m pip install django==%DJANGO_VERSION%"
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "%PYTHON%\\python.exe manage.py test"
