environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    # -------- PYTHON 2.7, Django 1.10 --------

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 2.7, Django 1.11b1 --------

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.4, Django 1.10 --------

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 3.4, Django 1.11b1 --------

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.5, Django 1.10 --------

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57

    # -------- PYTHON 3.5, Django 1.11b1 --------

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57

    # -------- PYTHON 3.6, Django 1.11b1 --------

    - PYTHON: "36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1

    - PYTHON: "36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014

    - PYTHON: "36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016

    - PYTHON: "36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57


platform:
  - x64

image: Visual Studio 2015

init:
- cmd: net start %SQL%

install:
  - cmd: SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%

  - cmd: python -m pip install lxml==3.6.0
  - "pip install wheel"
  - ps: wget 'https://github.com/PyMySQL/mysqlclient-python/releases/download/1.3.8/mysqlclient-1.3.9-cp27-cp27m-win_amd64.whl' -OutFile "$pwd\mysqlclient-1.3.9-cp27-cp27m-win_amd64.whl"
  - "pip install mysqlclient-1.3.9-cp27-cp27m-win_amd64.whl"
  - cmd: sed -e '/mysqlclient==1.3.10/ s/^#*/#/' -i requirements.txt
  - cmd: sed -e '/lxml==3.7.3/ s/^#*/#/' -i requirements.txt
  - cmd: "python -m pip install -r requirements.txt"
  - cmd: "python -m pip install django==%DJANGO_VERSION%"
  - cmd: nuget install redis-64 -excludeversion
  - cmd: redis-64\tools\redis-server.exe --service-install
  - cmd: redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "python manage.py test"
