environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    
    # -------- PYTHON 2.7, Django 1.10 --------

    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57
    
    # -------- PYTHON 2.7, Django 1.11b1 --------

    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python27-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57
      
    # -------- PYTHON 3.4, Django 1.10 --------

    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57
    
    # -------- PYTHON 3.4, Django 1.11b1 --------

    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python34-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57
      
    # -------- PYTHON 3.5, Django 1.10 --------

    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.10"
      SQL: MySQL57
    
    # -------- PYTHON 3.5, Django 1.11b1 --------

    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python35-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57
      
    # -------- PYTHON 3.6, Django 1.11b1 --------

    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2012SP1
      
    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2014
      
    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MSSQL$SQL2016
      
    - PYTHON: "C:\\Python36-x64"
      DJANGO_VERSION: "1.11b1"
      SQL: MySQL57


platform:
  - x86
  
init:
- cmd: net start %SQL%

install:
  - "curl -fsS -o lxml-3.7.3-cp27-cp27m-win_amd64.whl 'http://www.lfd.uci.edu/~gohlke/pythonlibs/tugh5y6k/lxml-3.7.3-cp27-cp27m-win_amd64.whl' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://www.lfd.uci.edu/~gohlke/pythonlibs/' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed"
  - "%PYTHON%\\python.exe -m pip install lxml-3.7.3-cp27-cp27m-win_amd64.whl"
  - "curl -fsS -o mysqlclient-1.3.10-cp27-cp27m-win_amd64.whl 'http://www.lfd.uci.edu/~gohlke/pythonlibs/tugh5y6k/mysqlclient-1.3.10-cp27-cp27m-win_amd64.whl' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://www.lfd.uci.edu/~gohlke/pythonlibs/' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed"
  - "%PYTHON%\\python.exe -m pip install mysqlclient-1.3.10-cp27-cp27m-win_amd64.whl"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install django==%DJANGO_VERSION%"
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "%PYTHON%\\python.exe manage.py test"
