language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11b1
matrix:
  exclude: # combinations we want to exclude
    - python: "3.6"
      env: DJANGO_VERSION=1.10
    - python: "3.6-dev"
      env: DJANGO_VERSION=1.10
# services
services:
  - mysql
  - redis-server
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION
# command to run tests
script: ./manage.py test
