sudo: false
language: python
cache: pip
python: 3.6


before_install:
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password123?' -p 1433:1433 -d microsoft/mssql-server-linux:latest

install:
  - pip install django-pyodbc-azure==1.11.15.0
  - pip install django==$DJANGO_VERSION
  
script:
  - ./manage.py test -v2
