sudo: false
language: python
cache: pip



matrix:
  include:
    - os: windows
      language: sh
      python: "3.6"
      env: DJANGO_VERSION=1.11
      before_install:
        - choco install python3 --version 3.6.6
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        
        - choco install sql-server-2016-developer-edition

install:

  - pip install django==$DJANGO_VERSION
  
script:
  - ./manage.py test -v2
