sudo: false
language: python
cache: pip

services:
  - redis-server

matrix:
  include:
    - python: "2.7"
      dist: trusty
      env: DJANGO_VERSION=1.11

    - python: "2.7"
      dist: trusty
      env: DJANGO_VERSION=1.11

    - os: windows
      language: sh
      python: "3.6"
      env: DJANGO_VERSION=1.11
      before_install:
        - choco install python3 --version 3.6.6
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        
        - choco install redis-64

install:

  - pip install django==$DJANGO_VERSION
  
script:
  - redis-cli PING
  - ./manage.py test
